apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepquantum-algorithm-test
  namespace: test
  labels:
    k8s-app: deepquantum-algorithm-test
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: deepquantum-algorithm-test
  template:
    metadata:
      labels:
        app: deepquantum-algorithm-test

    spec:
      imagePullSecrets:
        - name: registry-harbor
      automountServiceAccountToken: false
      containers:
        - name: deepquantum-algorithm-test
          image: 192.168.20.55/test_api_project/20260318
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          resources:
            limits:
              cpu: 1
              memory: 3Gi
              ephemeral-storage: 20Gi
            requests:
              cpu: 300m
              memory: 1Gi
              ephemeral-storage: 2Gi
          volumeMounts:
            - name: deepquantum-algorithm-test-logs
              mountPath: /deepquantum-algorithm-test-logs
      volumes:
        - name: deepquantum-algorithm-test-logs
          persistentVolumeClaim:
            claimName: logs-test

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deepquantum-algorithm-test
  name: deepquantum-algorithm-test
  namespace: test
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30097
  selector:
    app: deepquantum-algorithm-test


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-http-deepquantum-algorithm-test
  namespace: test
spec:
  ingressClassName: "nginx"
  rules:
    - host: dqapi-dev.turingq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deepquantum-algorithm-test
                port:
                  number: 80
